# Generated by Django 2.1.3 on 2018-11-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('bahia', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
    ]
