# Generated by Django 2.1.3 on 2018-11-30 07:42

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('pais', django_countries.fields.CountryField(default='SV', max_length=2)),
                ('telefono', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('bahia', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=25)),
                ('cantidad', models.IntegerField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('contenedor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NavieraSkyApp.Contenedor')),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('pais', django_countries.fields.CountryField(default='SV', max_length=2)),
                ('telefono', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=25)),
                ('cantidad', models.IntegerField()),
                ('fecha_salida', models.DateField()),
                ('contenedor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NavieraSkyApp.Contenedor')),
                ('motorista', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NavieraSkyApp.Motorista')),
                ('producto', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NavieraSkyApp.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='ingreso',
            name='motorista',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NavieraSkyApp.Motorista'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='producto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NavieraSkyApp.Producto'),
        ),
    ]
